name = "lucky-zodiac-worker"
main = "src/index.js"
compatibility_date = "2025-04-28"

[vars]
# 환경 변수에서 직접 넣는 대신 wrangler secret으로 등록되어 있다면 생략 가능
# GEMINI_API_KEY = "AIzaSyCwhypGNz8ExfrzrpJbcjsZiG_ZORTCAQ4"